51-feature/table: Data Table Features and Codebase Refactor
Lands-Horizon-Corp/horizon-corp pull request #57
Opened 2024-11-26 01:55 UTC by Jervx

## **Description**
This PR introduces new **Data Table features** and includes refactoring and cleanup tasks to improve the codebase.

---

## **Features**

### **Data Table Features**
- **Column Pinning**
  - Pin columns to the left, right, or center (default).
- **Column Resizing**
  - Enable resizing for pinned columns.
- **Column Reordering**
  - Drag-and-drop functionality to reorder columns.
- **Server-Side Data Management**
  - Filtering, sorting, and pagination handled server-side.
- **Data Export**
  - Export options for:
    - Selected rows.
    - Current page.
    - All filtered rows.
    - All unfiltered rows.
- **Delete Selected Rows**
  - Bulk deletion functionality for selected rows.

---

## **Refactor and Cleanup**
- **Icons Refactor**
  - Renamed icons for better consistency.
  - Updated imports and exports to align with the new naming convention.
- **Removed Unnecessary Files**
  - Removed `*.tsbuildinfo` files from Git tracking.
- **Codebase Formatting**
  - Reformatted the codebase for consistent styling.

---

Screenshot
![image](https://github.com/user-attachments/assets/deb26e97-ed72-4b77-b97b-cff5844568bf)

Merging this PR will close #51

2024-11-26 02:18 UTC, zalven-official reviewed
To make the `syncRowHeights` and `syncFooterRowHeights` functions reusable, we can abstract out the common logic into a generalized function that handles both rows and footer rows. This way, you can call the function for different tables (rows or footer rows) while keeping the code DRY (Don't Repeat Yourself).

Here's how you can refactor it:

### Step 1: Create a generic function to synchronize heights

```tsx
const syncHeights = useCallback(
    (tableRefs: React.RefObject<HTMLElement>[], rowDataAttr: string, idAttr: string) => {
        const rowIds = new Set<string>();

        // Collect all row IDs from each table
        tableRefs.forEach((tableRef) => {
            const rows = tableRef.current?.querySelectorAll(`[${rowDataAttr}]`);
            if (rows) {
                rows.forEach((row) =>
                    rowIds.add((row as HTMLElement).dataset[idAttr]!)
                );
            }
        });

        // Sync the heights for each rowId
        rowIds.forEach((rowId) => {
            const rows = tableRefs
                .map((tableRef) =>
                    tableRef.current?.querySelector(
                        `[${rowDataAttr}="${rowId}"]`
                    )
                )
                .filter(Boolean) as HTMLElement[];

            let maxHeight = 0;
            rows.forEach((row) => {
                row.style.height = 'auto';
                maxHeight = Math.max(maxHeight, row.offsetHeight);
            });

            rows.forEach((row) => {
                row.style.height = `${maxHeight}px`;
            });
        });
    },
    []
);
```

### Step 2: Use the generic function for row heights and footer row heights

Now, you can call `syncHeights` for both row and footer row heights by passing in the appropriate table references and data attributes.

For `syncRowHeights`:

```tsx
const syncRowHeights = useCallback(() => {
    syncHeights(
        [leftTableRef, centerTableRef, rightTableRef],
        'data-row-id',
        'rowId'
    );
}, [syncHeights]);
```

For `syncFooterRowHeights`:

```tsx
const syncFooterRowHeights = useCallback(() => {
    syncHeights(
        [leftTableRef, centerTableRef, rightTableRef],
        'data-footer-row-id',
        'footerRowId'
    );
}, [syncHeights]);
```

### Explanation

1. **syncHeights** is a reusable function that accepts:
   - `tableRefs`: An array of `React.RefObject<HTMLElement>` references to your left, center, and right table containers.
   - `rowDataAttr`: The attribute that holds the row ID (`data-row-id` for rows or `data-footer-row-id` for footers).
   - `idAttr`: The data attribute key (`rowId` or `footerRowId`).

2. The function works by:
   - Collecting all the unique row IDs across all tables using the `rowDataAttr` and `idAttr` attributes.
   - Then, it calculates the maximum height for each row and sets the height for all matching rows in each table to this value.

### Advantages of this approach:
- **Reusability**: You can use this single function to handle both rows and footer rows, avoiding repetition.
- **Scalability**: You can easily extend this to support more tables or attributes in the future.
- **Maintainability**: Changes to the height synchronization logic are centralized, making the code easier to maintain.

Let me know if you need further modifications!

2024-11-26 04:30 UTC, zalven-official requested changes
To make the `syncRowHeights` and `syncFooterRowHeights` functions reusable, we can abstract out the common logic into a generalized function that handles both rows and footer rows. This way, you can call the function for different tables (rows or footer rows) while keeping the code DRY (Don't Repeat Yourself).

Here's how you can refactor it:

### Step 1: Create a generic function to synchronize heights

```tsx
const syncHeights = useCallback(
    (tableRefs: React.RefObject<HTMLElement>[], rowDataAttr: string, idAttr: string) => {
        const rowIds = new Set<string>();

        // Collect all row IDs from each table
        tableRefs.forEach((tableRef) => {
            const rows = tableRef.current?.querySelectorAll(`[${rowDataAttr}]`);
            if (rows) {
                rows.forEach((row) =>
                    rowIds.add((row as HTMLElement).dataset[idAttr]!)
                );
            }
        });

        // Sync the heights for each rowId
        rowIds.forEach((rowId) => {
            const rows = tableRefs
                .map((tableRef) =>
                    tableRef.current?.querySelector(
                        `[${rowDataAttr}="${rowId}"]`
                    )
                )
                .filter(Boolean) as HTMLElement[];

            let maxHeight = 0;
            rows.forEach((row) => {
                row.style.height = 'auto';
                maxHeight = Math.max(maxHeight, row.offsetHeight);
            });

            rows.forEach((row) => {
                row.style.height = `${maxHeight}px`;
            });
        });
    },
    []
);
```

### Step 2: Use the generic function for row heights and footer row heights

Now, you can call `syncHeights` for both row and footer row heights by passing in the appropriate table references and data attributes.

For `syncRowHeights`:

```tsx
const syncRowHeights = useCallback(() => {
    syncHeights(
        [leftTableRef, centerTableRef, rightTableRef],
        'data-row-id',
        'rowId'
    );
}, [syncHeights]);
```

For `syncFooterRowHeights`:

```tsx
const syncFooterRowHeights = useCallback(() => {
    syncHeights(
        [leftTableRef, centerTableRef, rightTableRef],
        'data-footer-row-id',
        'footerRowId'
    );
}, [syncHeights]);
```

### Explanation

1. **syncHeights** is a reusable function that accepts:
   - `tableRefs`: An array of `React.RefObject<HTMLElement>` references to your left, center, and right table containers.
   - `rowDataAttr`: The attribute that holds the row ID (`data-row-id` for rows or `data-footer-row-id` for footers).
   - `idAttr`: The data attribute key (`rowId` or `footerRowId`).

2. The function works by:
   - Collecting all the unique row IDs across all tables using the `rowDataAttr` and `idAttr` attributes.
   - Then, it calculates the maximum height for each row and sets the height for all matching rows in each table to this value.

### Advantages of this approach:
- **Reusability**: You can use this single function to handle both rows and footer rows, avoiding repetition.
- **Scalability**: You can easily extend this to support more tables or attributes in the future.
- **Maintainability**: Changes to the height synchronization logic are centralized, making the code easier to maintain.

Let me know if you need further modifications!

2024-11-26 04:30 UTC, zalven-official commented on client/src/components/data-table/data-table-footer-aggregations/data-table-footer-summation.tsx
> +    sumAll?: boolean
delete all

2024-11-26 04:30 UTC, zalven-official commented on client/src/components/data-table/data-table-footer-aggregations/data-table-footer-summation.tsx
> +        const rows = sumAll
Delete sum all

2024-11-26 04:30 UTC, zalven-official commented on client/src/components/data-table/data-table-row-actions/index.tsx
Make all function arrow something ()=>

2024-11-26 04:30 UTC, zalven-official commented on client/src/components/data-table/data-table-selection-indicator.tsx
Removed unused components

2024-11-26 04:30 UTC, zalven-official commented on client/src/components/data-table/data-table-virtualize.tsx
Please add comment for this unused desyo

2024-11-26 04:30 UTC, zalven-official commented on client/src/components/data-table/hooks/use-datatable-state.ts
> +        pageSize: 10,
make props and default page size in constant/table.ts

2024-11-26 04:30 UTC, zalven-official commented on client/src/components/data-table/data-table-column-header/column-filters/multi-select-filter.tsx
Make this global

2024-11-26 04:49 UTC, zalven-official commented
Add global search and search injectables 

<img width="1597" alt="image" src="https://github.com/user-attachments/assets/52d9e7fc-2e5a-4381-bbda-7b80860c2acd">
<img width="196" alt="image" src="https://github.com/user-attachments/assets/db0b1da0-7f2f-4bc5-bebd-502fe16c190d">
<img width="1279" alt="image" src="https://github.com/user-attachments/assets/f5d85e34-e446-4486-9ee5-99866c3b0574">

2024-11-26 04:52 UTC, zalven-official commented
<img width="550" alt="image" src="https://github.com/user-attachments/assets/7801ec1a-1bca-4f4a-a7e6-f06e6c622d09">
Applying filter

2024-11-28 07:11 UTC, zalven-official approved these changes
LGTM!

2024-11-28 07:11 UTC, merged

2024-11-28 07:11 UTC, Jervx commented
Augh shems

2024-11-29 00:09 UTC, Jervx commented
close #51